spring:
  application:
    name: practice-tdd
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/practice_tdd
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create

local.server.port: 8080